version: "3"
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - jira
      - confluence
      - bamboo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
